name: Build Rocky Rootfs

on:
  workflow_dispatch:
  schedule:
    - cron : '0 0 1 * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create Docker Container
      run: docker run -d --name rocky-wsl rockylinux/rockylinux:latest
    - name: Export Docker Container to rootfs
      run: docker export rocky-wsl -o rootfs.tar
    - name: Upload rootfs
      uses: actions/upload-artifact@v2
      with:
        name: rootfs
        path: rootfs.tar
