name: Test-Release

on:
  workflow_dispatch:
  schedule:
    - cron : '0 0 1 * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create Docker Container
      run: docker run -d --name rocky-wsl rockylinux/rockylinux:latest
    - name: Export Docker Container to rootfs
      run: docker export rocky-wsl -o rootfs.tar
    - name: Compress Rel in Zip
      run: zip -r Rel.zip ./ -x '*.git*' -x '*.github*'
      
    - name: Clean Directory
      run: rm -v !(*.zip)
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Automated Release"
          files: |
            Rel.zip
